const Projects = [
  {
    id: 1,
    category: 'Html/Css',
    link1: 'competent-sammet-a965b4.netlify.app/',
    link2: 'https://github.com/amirai0396/travelly-project',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Travelly',
  },
  {
    id: 2,
    category: 'Javascript',
    link1: 'https://angry-ardinghelli-5c288f.netlify.app/',
    link2: 'https://github.com/amirai0396/money-grow',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Money-Grow',
  },
  {
    id: 3,
    category: 'Animation',
    link1: 'https://quizzical-yonath-dc1ad2.netlify.app/',
    link2: 'https://github.com/amirai0396/money-grow-webpage',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Money-grow',
  },
  {
    id: 4,
    category: 'React Js',
    link1: 'www.youtube.com',
    link2: 'https://github.com/amirai0396/Crown-clothing',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Crown-Clothing',
  },
  {
    id: 5,
    category: 'Javascript',
    link1: 'https://github.com/amirai0396/pureJs-Ecommerce',
    link2: 'wooden-homes.netlify.app/',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Vanilla Javascript E-commerce',
  },
  {
    id: 6,
    category: 'React Js',
    link1: 'unruffled-dijkstra-d25ab9.netlify.app',
    link2: 'https://github.com/amirai0396/Tour-',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Tour',
  },
  {
    id: 7,
    category: 'React Js',
    link1: 'www.youtube.com',
    link2: 'https://github.com/amirai0396/monsters-pub',
    icon1: 'G',
    icon2: 'Y',
    image: '',
    title: 'Monsters-Pub',
  },
];

export default Projects;
